### ISSUE TITLE
GitHub joins Microsoft: A Toast from GitHub Alumni

### ISSUE THREAD

**Issue by schaar** [xubbers/toasts#1]
**To the GitHub Team**,

Congratulations on [your acquisition by Microsoft](https://blogs.microsoft.com/blog/2018/06/04/microsoft-github-empowering-developers/)!

Our experiences at GitHub have all varied in scope and time, but as Xubbers, we're all glad to say we've been part of the journey.   

Milestones at GitHub have been often celebrated with an issue in the `Toasts` repo. We felt like this was too significant of an announcement to pass up. Congrats again. ❤️  

![photo on 6-4-18 at 8 18 am 2](https://user-images.githubusercontent.com/3597934/40925986-f1b058b6-67cf-11e8-99d6-402e7592e9f6.jpg)

**Comment by orderedlist** [comment]
![photo on 6-4-18 at 11 25 am 2](https://user-images.githubusercontent.com/1680/40926342-f8e59424-67e9-11e8-8dbb-360d064e30bd.jpg)

**Comment by adelcambre** [comment]
![d0578409-0bb4-411b-90b1-89949500227e](https://user-images.githubusercontent.com/242/40926785-56ed441e-67da-11e8-85d6-b9477c909267.jpeg)

**Comment by aspires** [comment]
![photo on 6-4-18 at 10 45 am](https://user-images.githubusercontent.com/774297/40927469-69ddc3fa-67e4-11e8-8c66-b35766aac54e.jpg)

**Comment by chrishunt** [comment]
![toast](https://user-images.githubusercontent.com/65323/40927481-ac70e9d8-67d3-11e8-82f2-3a38e8e9326b.jpg)

**Comment by tlberglund** [comment]
So happy for all my GitHub friends past and present! Congratulations on a great new partnership.

![img_1951](https://user-images.githubusercontent.com/63223/40928119-c8478b4e-67dd-11e8-948a-ba5bf54b54c8.jpg)

**Comment by pmn** [comment]
![toast](https://user-images.githubusercontent.com/279389/40928214-a5031a84-67d5-11e8-838e-788749308513.jpg)

**Comment by bnferguson** [comment]
![image](https://user-images.githubusercontent.com/47749/40928289-39707ffe-6821-11e8-8572-beb74db5d519.png)

**Comment by mattgraham** [comment]
![img_3986](https://user-images.githubusercontent.com/51578/40928620-04978e70-67f0-11e8-99af-588be1e2f5fc.JPG)

**Comment by rick** [comment]
![img_20180604_095652](https://user-images.githubusercontent.com/6259/40930848-ba47772a-67dd-11e8-9e29-7caeee1eebca.jpg)

**Comment by lstoll** [comment]
![photo on 6-4-18 at 12 04 2](https://user-images.githubusercontent.com/694/40931112-77034644-67ef-11e8-8d85-2d91bd925b29.jpg)

**Comment by davideg** [comment]
![cheersgithub](https://user-images.githubusercontent.com/395397/40931689-d4a96e54-67e0-11e8-8e9d-0e92646dfdc4.jpg)

**Comment by lindsay** [comment]
![img_4547](https://user-images.githubusercontent.com/10743534/40932363-62ccebc8-682e-11e8-9ee8-409f53827629.jpg)

edit: he was a turnt beer

**Comment by watsonian** [comment]
![photo on 6-4-18 at 10 41 am](https://user-images.githubusercontent.com/244/40932676-fa0edeb0-67e3-11e8-98f4-1283893a1b61.jpg)

**Comment by bryanveloso** [comment]
![](https://user-images.githubusercontent.com/1258/40934707-7f0a2fd8-67ea-11e8-8ce5-7c18c4e11fd5.JPG)

**Comment by pengwynn** [comment]
![photo on 6-4-18 at 1 38 pm](https://user-images.githubusercontent.com/865/40935109-aca8b038-67fc-11e8-811d-3b52132a85f9.jpg)

**Comment by devinreams** [comment]
![photo on 6-4-18 at 12 43 pm 2](https://user-images.githubusercontent.com/49511/40935300-e333d36a-67f4-11e8-9af1-f598f9c56880.jpg)

**Comment by lizclink** [comment]
![photo on 6-4-18 at 11 56 am](https://user-images.githubusercontent.com/2566204/40935923-7ce6a0ac-67ee-11e8-9247-876cfdb687d7.jpg)

**Comment by sr** [comment]
![whatsapp image 2018-06-04 at 13 25 39](https://user-images.githubusercontent.com/90/40935845-5f4755a0-6807-11e8-9ddf-349f7d821421.jpeg)

**Comment by sonyagreen** [comment]
![photo on 6-4-18 at 11 35 am](https://user-images.githubusercontent.com/1054720/40936795-818a8206-680a-11e8-886b-723682013965.jpg)

**Comment by joewadcan** [comment]
Here's to us!

![image](https://user-images.githubusercontent.com/1266306/40938010-5aecf58a-67f5-11e8-9784-f6a931381f87.png)

**Comment by nmsanchez** [comment]
![photo on 6-4-18 at 12 55 pm 2](https://user-images.githubusercontent.com/8992831/40938500-ea1e01da-67f6-11e8-80c1-20b6c795fa20.jpg)

**Comment by daniloc** [comment]
😘
![browserpreview_tmp-1](https://user-images.githubusercontent.com/213358/40938935-458166b0-6811-11e8-8a22-9839ff832bdb.gif)

**Comment by derekgr** [comment]
![img_20180604_141026 1](https://user-images.githubusercontent.com/60566/40939302-7f3c8e94-6801-11e8-8062-687d5eeb50c4.jpg)

**Comment by danishkhan** [comment]
![photo on 6-4-18 at 1 17 pm](https://user-images.githubusercontent.com/19433/40939497-abb87c56-67f9-11e8-8114-b7e444d05e06.jpg)

**Comment by holman** [comment]
![59b217e0-ab7f-4ffa-aa66-deeabf1cabdd](https://user-images.githubusercontent.com/2723/40940569-84ce4e50-6848-11e8-9af0-0d1d26cd3f8f.JPG)

**Comment by dq-turtle** [comment]
<img width="437" alt="screen shot 2018-06-04 at 2 32 45 pm" src="https://user-images.githubusercontent.com/12905102/40942843-31bb44e6-6804-11e8-8905-e918ec9634c0.png">

**Comment by jfryman** [comment]
![photo on 6-4-18 at 2 46 pm 2](https://user-images.githubusercontent.com/20028/40943485-2822c2a4-6806-11e8-9dc3-dde3ed923fc6.jpg)

**Comment by briandoll** [comment]
❤️ 👍 🚢 🚀 

![cheers](https://user-images.githubusercontent.com/4590/40943609-99f4b59a-6806-11e8-9971-e618f0d86281.jpg)

**Comment by bhuga** [comment]
![photo on 6-4-18 at 3 53 pm](https://user-images.githubusercontent.com/12676/40943713-64318eac-680f-11e8-8ff0-339d7283cbfc.jpg)

**Comment by jglovier** [comment]
![image](https://user-images.githubusercontent.com/1319791/40955652-54b73b3a-6859-11e8-93f9-0044a6f9c5f6.png)

**Comment by cobyism** [comment]
![photo on 05-06-2018 at 17 57](https://user-images.githubusercontent.com/296432/40990825-e66bdd84-68e9-11e8-9dd7-356c89d61522.jpg)

**Comment by ben** [comment]
![img_1466](https://user-images.githubusercontent.com/39902/41053997-fef11d1e-6971-11e8-9e13-6787b1603be7.JPG)
